### ISSUE TITLE
打包后运行release版本apk闪退

### ISSUE THREAD

**Issue by bigkrys** [wonday/react-native-aliyun-push#121]
2019-11-19 10:44:19.574 2417-2417/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.egame_android, PID: 2417
    java.lang.ExceptionInInitializerError
        at f.a.b.a.a.a.f.c.a(Unknown Source:0)
        at f.a.b.a.a.a.e.c.a(Unknown Source:2)
        at com.alibaba.sdk.android.push.n.a.a(Unknown Source:18)
        at com.egame_android.MainApplication.a(Unknown Source:3)
        at com.egame_android.MainApplication.onCreate(Unknown Source:3)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.IllegalStateException: Fail to load ams-spi-services for f.a.b.a.a.a.f.a
        at f.a.b.a.a.a.f.d.a(Unknown Source:46)
        at f.a.b.a.a.a.f.b.<clinit>(Unknown Source:13)
        at f.a.b.a.a.a.f.c.a(Unknown Source:0) 
        at f.a.b.a.a.a.e.c.a(Unknown Source:2) 
        at com.alibaba.sdk.android.push.n.a.a(Unknown Source:18) 
        at com.egame_android.MainApplication.a(Unknown Source:3) 
        at com.egame_android.MainApplication.onCreate(Unknown Source:3) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:273) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.alibaba.sdk.android.push.securitybox.alipush.AliPushSecurityBoxServiceFactoryProvider" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.egame_android-8MurT5oJr7gRv4VTdUXGTw==/base.apk"],nativeLibraryDirectories=[/data/app/com.egame_android-8MurT5oJr7gRv4VTdUXGTw==/lib/arm64, /data/app/com.egame_android-8MurT5oJr7gRv4VTdUXGTw==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at f.a.b.a.a.a.f.d.a(Unknown Source:11)
        at f.a.b.a.a.a.f.b.<clinit>(Unknown Source:13) 
        at f.a.b.a.a.a.f.c.a(Unknown Source:0) 
        at f.a.b.a.a.a.e.c.a(Unknown Source:2) 
        at com.alibaba.sdk.android.push.n.a.a(Unknown Source:18) 
        at com.egame_android.MainApplication.a(Unknown Source:3) 
        at com.egame_android.MainApplication.onCreate(Unknown Source:3) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717) 
        at android.app.ActivityThread.access$2000(ActivityThread.java:273) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 

react-native 版本0.58.6
react-native-aliyun-push版本1.0.17

**Comment by PhantomRay** [comment]
你好，我也遇到类似的问题，请问您是怎么解决的。
