### ISSUE TITLE
部分手机运行崩溃

### ISSUE THREAD

**Issue by bigkrys** [wonday/react-native-aliyun-push#123]
在部分手机上运行会崩溃，但是把MainApplication.java下面原本设置的
` @Override
  public void onCreate() {
    super.onCreate();
    //下面是添加的代码
      //  this.initCloudChannel(this);
        //添加结束
    SoLoader.init(this, /* native exopackage */ false);
  }`
里面的 this.initCloudChannel(this);注释掉，app正常运行。

log cat报错主要如下
FATAL EXCEPTION: main
    Process: com.egame_android, PID: 10185
    java.lang.ExceptionInInitializerError
        at f.a.b.a.a.a.f.c.a(Unknown Source:0)
        at f.a.b.a.a.a.e.c.a(Unknown Source:2)
        at com.alibaba.sdk.android.push.j.a.a(Unknown Source:18)
        at com.egame_android.MainApplication.a(Unknown Source:3)
        at com.egame_android.MainApplication.onCreate(Unknown Source:3)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.IllegalStateException: Fail to load ams-spi-services for f.a.b.a.a.a.f.a
        at f.a.b.a.a.a.f.d.a(Unknown Source:46)
        at f.a.b.a.a.a.f.b.<clinit>(Unknown Source:13)
        at f.a.b.a.a.a.f.c.a(Unknown Source:0)
        at f.a.b.a.a.a.e.c.a(Unknown Source:2)
        at com.alibaba.sdk.android.push.j.a.a(Unknown Source:18)
        at com.egame_android.MainApplication.a(Unknown Source:3)
        at com.egame_android.MainApplication.onCreate(Unknown Source:3)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1162)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6717)
        at android.app.ActivityThread.access$2000(ActivityThread.java:273)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2020)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

react-natiive版本0.58.6

**Comment by bigkrys** [comment]
https://help.aliyun.com/knowledge_detail/39998.html?spm=a2c6h.13066369.0.0.59924697EOzwJp
阿里云官方有这个文档，但是这个怎么运用在react-native-aliyun-push里面进行修改呢？
