### ISSUE TITLE
IOS simulator 下 getDeviceId 报错

### ISSUE THREAD

**Issue by hellobbq** [wonday/react-native-aliyun-push#25]
```
ExceptionsManager.js:73 Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]' was thrown while invoking getDeviceId on target AliyunPush with params (
    49
)
callstack: (
	0   CoreFoundation                      0x000000010dbd71e6 __exceptionPreprocess + 294
	1   libobjc.A.dylib                     0x000000010c04d031 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010dc170bc _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010dae445d -[__NSPlaceholderArray initWithObjects:count:] + 237
	4   CoreFoundation                      0x000000010daeae24 +[NSArray arrayWithObjects:count:] + 52
	5   TestApp                             0x0000000109f5ac21 -[AliyunPushManager getDeviceId:] + 145
	6   CoreFoundation                      0x000000010db5accc __invoking___ + 140
	7   CoreFoundation                      0x000000010db5ab84 -[NSInvocation invoke] + 308
	8   CoreFoundation                      0x000000010db738d6 -[NSInvocation invokeWithTarget:] + 54
	9   TestApp                             0x0000000109c0d5ec -[RCTModuleMethod invokeWithBridge:module:arguments:] + 2796
	10  TestApp                             0x0000000109cc0d92 _ZN8facebook5reactL11invokeInnerEP9RCTBridgeP13RCTModuleDatajRKN5folly7dynamicE + 786
	11  TestApp                             0x0000000109cc08bf _ZZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEiENK3$_0clEv + 127
	12  TestApp                             0x0000000109cc0839 ___ZN8facebook5react15RCTNativeModule6invokeEjON5folly7dynamicEi_block_invoke + 25
	13  libdispatch.dylib                   0x00000001128b573b _dispatch_call_block_and_release + 12
	14  libdispatch.dylib                   0x00000001128b6779 _dispatch_client_callout + 8
	15  libdispatch.dylib                   0x00000001128be1b2 _dispatch_queue_serial_drain + 735
	16  libdispatch.dylib                   0x00000001128be9af _dispatch_queue_invoke + 321
	17  libdispatch.dylib                   0x00000001128bb16a _dispatch_queue_override_invoke + 477
	18  libdispatch.dylib                   0x00000001128c0cf8 _dispatch_root_queue_drain + 473
	19  libdispatch.dylib                   0x00000001128c0ac1 _dispatch_worker_thread3 + 119
	20  libsystem_pthread.dylib             0x0000000112dd81ca _pthread_wqthread + 1387
	21  libsystem_pthread.dylib             0x0000000112dd7c4d start_wqthread + 13
)
```
请问是什么原因？

react native: 0.54.4
aliyun-push: latest

**Comment by wonday** [comment]
看不出来哪里出错，我的环境不报错。手机环境报错吗？
不过ios simulator是不能接受推送的， 苹果公司好像有限制。

**Comment by hellobbq** [comment]
@wonday 暂时没办法用真机测试，等之后测试后回报你结果。

不过更新到1.0.9之后启动闪退，报错如下
```
Process: com.testApp, PID: 4621
   java.lang.NoClassDefFoundError: com.alibaba.sdk.android.push.impl.k
       at com.alibaba.sdk.android.push.impl.j.a(Unknown Source)
       at com.alibaba.sdk.android.push.noonesdk.PushServiceFactory.init(Unknown Source)
       at com.testApp.MainApplication.initCloudChannel(MainApplication.java:87)
       at com.testApp.MainApplication.onCreate(MainApplication.java:79)
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
       at android.app.ActivityThread.access$1500(ActivityThread.java:151)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5254)
       at java.lang.reflect.Method.invoke(Native Method)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

yarn upgrade ...

**Comment by wonday** [comment]
今天重新修正了一下，发布了v1.0.10, 麻烦测试一下看看是否还有问题。

**Comment by hellobbq** [comment]
109的更新错误修复了，谢谢
