### ISSUE TITLE
升级到最新版本报错   java.lang.NoClassDefFoundError: com.alibaba.sdk.android.push.impl.k

### ISSUE THREAD

**Issue by cuiken** [wonday/react-native-aliyun-push#29]
升级到1.0.9后，编译能通过，但是app启动闪退

`V/fb-UnpackingSoSource: not releasing dso store lock for /data/user/0/com.elinter.app.powerview/lib-main (syncer thread started)
I/SecurityBoxService: Aliyun
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.alibaba.sdk.android.push.impl.k>
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.alibaba.sdk.android.push.impl.k>
I/MPS:CloudPushService: [AMS]Initialize Mobile Push service...
W/AppMonitor: load ut_c_api.so failed
I/art: Rejecting re-init on previously-failed class java.lang.Class<com.alibaba.sdk.android.push.impl.k>
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.elinter.app.powerview, PID: 3384
                  java.lang.NoClassDefFoundError: com.alibaba.sdk.android.push.impl.k
                      at com.alibaba.sdk.android.push.impl.j.a(Unknown Source)
                      at com.alibaba.sdk.android.push.noonesdk.PushServiceFactory.init(Unknown Source)
                      at com.elinter.app.powerview.MainApplication.initCloudChannel(MainApplication.java:86)
                      at com.elinter.app.powerview.MainApplication.onCreate(MainApplication.java:76)
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1015)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4834)
                      at android.app.ActivityThread.access$1600(ActivityThread.java:168)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:150)
                      at android.app.ActivityThread.main(ActivityThread.java:5659)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)`

**Comment by wonday** [comment]
汗，昨天改完了竟然还是拿老版本测试的。
今天重新修正了一下，发布了v1.0.10, 麻烦测试一下看看是否还有问题。

**Comment by cuiken** [comment]
@wonday 没问题了
